In [2]:
## DATA FRAMES, DATA SERIRES, AND OPERATIONS IN PANDAS

In [3]:
import pandas as pd
import numpy as np

In [5]:
df= pd.DataFrame(np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3","Row4","Row5",],columns=["Column1","Column2","Column3","Column4"])

In [7]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [9]:
df.to_csv("red")

In [8]:
## ACCESING THE ELEMENTS
# 1. .loc
# 2. .iloc
df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64

In [13]:
type(df.loc["Row1"])

pandas.core.series.Series

In [11]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df.iloc[0:2,0:2]

      Column1  Column2
Row1        0        1
Row2        4        5

In [19]:
type(df.iloc[0:2,0:2])

pandas.core.frame.DataFrame

In [20]:
type(df.iloc[0:1,0:1])

pandas.core.frame.DataFrame

In [21]:
# CONVERT DATAFRAME INTO ARRAY

In [24]:
df.iloc[:,1:].values.shape

(5, 3)

In [23]:
df.iloc[:,1:].value_counts()

Column2  Column3  Column4
1        2        3          1
5        6        7          1
9        10       11         1
13       14       15         1
17       18       19         1
Name: count, dtype: int64

In [25]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [28]:
df["Column1"].value_counts() #get counts of numbers

Column1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [29]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [32]:
df["Column1"].unique()

array([ 0,  4,  8, 12, 16])

### READ DATA FROM CSV FILE

In [202]:
df = pd.read_csv("mercedesbenz.csv")

In [203]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [204]:
df.tail()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [206]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [207]:
df['X1'].value_counts()

X1
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
d       3
q       3
ab      3
Name: count, dtype: int64

In [214]:
df[(df['y']>100) & (df['X3']=='a')]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
291,584,105.23,z,b,a,a,d,i,j,a,...,0,1,0,0,0,0,0,0,0,0
299,597,108.43,ak,v,ao,a,d,i,i,l,...,0,1,0,0,0,0,0,0,0,0
450,877,111.74,v,s,as,a,d,d,g,u,...,0,1,0,0,0,0,0,0,0,0
640,1240,108.41,x,b,as,a,d,c,j,j,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4155,8304,106.34,w,s,as,a,d,aa,c,p,...,0,0,1,0,0,0,0,0,0,0
4176,8344,149.52,ak,l,as,a,d,aa,j,r,...,0,0,1,0,0,0,0,0,0,0
4186,8371,131.98,j,f,ar,a,d,aa,j,n,...,0,0,1,0,0,0,0,0,0,0
4188,8374,102.33,f,s,as,a,d,aa,d,t,...,0,0,1,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0

### STRINGIO AND BYTESIO

In [215]:
from io import StringIO,BytesIO

In [216]:
data = ('index,a,b\n'
        'x,2,3\n'
        'y,5,6\n'
        'z,8,9\n'
       )

In [217]:
type(data)

str

In [218]:
pd.read_csv(StringIO(data))

  index  a  b
0     x  2  3
1     y  5  6
2     z  8  9

In [219]:
df = pd.read_csv(StringIO(data), index_col=0)

In [220]:
df

       a  b
index
x      2  3
y      5  6
z      8  9

In [221]:
df.to_csv('results')

In [222]:
df

       a  b
index
x      2  3
y      5  6
z      8  9

In [223]:
df['a']

index
x    2
y    5
z    8
Name: a, dtype: int64

In [224]:
df = pd.read_csv(StringIO(data), usecols=['a','b'],  dtype={"a":float, "b":str})

In [225]:
df

     a  b
0  2.0  3
1  5.0  6
2  8.0  9

In [136]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,\n'
       )#leave comma at end

In [137]:
pd.read_csv(StringIO(data))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [138]:
pd.read_csv(StringIO(data), index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [141]:
#combining usecols and index_cols
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,\n'
       )#leave comma at end

In [142]:
pd.read_csv(StringIO(data), usecols=['b','c'])

     b   c
4  bat NaN
8  cow NaN

In [145]:
pd.read_csv(StringIO(data), usecols=['b','c'], index_col=False)

        b    c
0   apple  bat
1  orange  cow

In [146]:
# Quoting and escaping characters, useful for NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [147]:
pd.read_csv(StringIO(data), escapechar="\\")

                               a  b
0  hello, "Bob", nice to see you  5

### URL TO CSV

In [157]:
# url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
# df = pd.read_csv(url, sep='\t')
# print(df.head())
# Load into pandas
df = pd.read_csv("cu.item", sep='\t')
df.describe()

       display_level  sort_sequence
count     400.000000     400.000000
mean        3.195000     200.500000
std         1.815272     115.614301
min         0.000000       1.000000
25%         2.000000     100.750000
50%         3.000000     200.500000
75%         4.000000     300.250000
max         8.000000     400.000000

### JSON TO CSV

In [179]:
import pandas as pd
import json

sample_json = '{"users": [{"id": 1,"name": "Nabeel Rizvi","email": "nabeel@example.com","isActive": true,"roles": ["Admin", "Developer"]},{"id": 2,"name": "Sara Khan","email": "sara@example.com","isActive": false,"roles": ["Tester"]}],"meta": {"count": 2,"source": "Internal Database"}}'

# Load JSON string into a Python dict
data = json.loads(sample_json)

# Extract only the list under "users"
df = pd.json_normalize(data["users"])
df

   id          name               email  isActive               roles
0   1  Nabeel Rizvi  nabeel@example.com      True  [Admin, Developer]
1   2     Sara Khan    sara@example.com     False            [Tester]

In [181]:
data = '{"id": 1,"name": "Nabeel Rizvi","email": "nabeel@example.com","isActive": true,"roles": ["Admin", "Developer"]}'
df = pd.read_json(StringIO(data))

In [182]:
df

   id          name               email  isActive      roles
0   1  Nabeel Rizvi  nabeel@example.com      True      Admin
1   1  Nabeel Rizvi  nabeel@example.com      True  Developer

In [185]:
data = '{"id": 1,"name": "Nabeel Rizvi","email": "nabeel@example.com","isActive": true,"roles": 
[{"Project Role":"Admin"},
 { "Normal Role":"Developer"}]}'
df = pd.read_json(StringIO(data))
df

,id,name,email,isActive,roles
0,1,Nabeel Rizvi,nabeel@example.com,True,{'Project Role': 'Admin'}
1,1,Nabeel Rizvi,nabeel@example.com,True,{'Normal Role': 'Developer'}

In [187]:
data = '{"id": 1,"name": "Nabeel Rizvi","email": "nabeel@example.com","isActive": true,"roles":
[{"Project Role":"Admin",
  "Normal Role":"Developer"}]}'
df = pd.read_json(StringIO(data))
df

,id,name,email,isActive,roles
0,1,Nabeel Rizvi,nabeel@example.com,True,"{'Project Role': 'Admin', 'Normal Role': 'Deve..."

In [230]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [192]:
df.to_csv('wine')

In [196]:
# df.to_json('winejson')
df.to_json(orient="records")

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},{"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},{"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},{"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},{"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},{"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},{"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},{"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},{"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},{"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},{"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},{"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},{"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},{"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},{"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},{"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},{"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},{"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},{"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},{"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},{"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},{"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},{"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},{"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},{"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},{"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},{"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},{"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},{"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},{"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},{"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},{"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},{"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},{"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},{"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},{"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},{"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},{"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},{"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},{"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},{"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},{"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},{"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},{"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},{"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},{"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},{"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},{"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},{"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},{"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},{"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},{"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},{"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},{"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},{"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},{"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},{"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},{"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},{"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},{"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},{"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},{"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},{"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},{"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},{"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},{"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},{"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},{"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},{"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},{"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},{"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},{"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},{"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},{"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},{"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},{"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},{"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},{"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},{"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},{"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},{"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},{"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},{"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},{"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},{"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},{"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},{"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},{"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},{"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},{"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},{"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},{"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},{"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},{"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},{"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},{"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},{"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},{"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},{"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},{"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},{"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},{"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},{"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},{"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},{"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},{"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},{"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},{"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},{"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},{"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},{"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},{"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},{"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},{"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},{"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},{"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},{"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},{"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},{"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},{"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},{"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},{"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},{"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},{"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},{"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},{"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},{"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},{"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},{"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},{"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},{"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},{"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},{"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},{"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53,"9":0.75,"10":4.6,"11":0.77,"12":2.31,"13":600},{"0":3,"1":13.36,"2":2.56,"3":2.35,"4":20.0,"5":89,"6":1.4,"7":0.5,"8":0.37,"9":0.64,"10":5.6,"11":0.7,"12":2.47,"13":780},{"0":3,"1":13.52,"2":3.17,"3":2.72,"4":23.5,"5":97,"6":1.55,"7":0.52,"8":0.5,"9":0.55,"10":4.35,"11":0.89,"12":2.06,"13":520},{"0":3,"1":13.62,"2":4.95,"3":2.35,"4":20.0,"5":92,"6":2.0,"7":0.8,"8":0.47,"9":1.02,"10":4.4,"11":0.91,"12":2.05,"13":550},{"0":3,"1":12.25,"2":3.88,"3":2.2,"4":18.5,"5":112,"6":1.38,"7":0.78,"8":0.29,"9":1.14,"10":8.21,"11":0.65,"12":2.0,"13":855},{"0":3,"1":13.16,"2":3.57,"3":2.15,"4":21.0,"5":102,"6":1.5,"7":0.55,"8":0.43,"9":1.3,"10":4.0,"11":0.6,"12":1.68,"13":830},{"0":3,"1":13.88,"2":5.04,"3":2.23,"4":20.0,"5":80,"6":0.98,"7":0.34,"8":0.4,"9":0.68,"10":4.9,"11":0.58,"12":1.33,"13":415},{"0":3,"1":12.87,"2":4.61,"3":2.48,"4":21.5,"5":86,"6":1.7,"7":0.65,"8":0.47,"9":0.86,"10":7.65,"11":0.54,"12":1.86,"13":625},{"0":3,"1":13.32,"2":3.24,"3":2.38,"4":21.5,"5":92,"6":1.93,"7":0.76,"8":0.45,"9":1.25,"10":8.42,"11":0.55,"12":1.62,"13":650},{"0":3,"1":13.08,"2":3.9,"3":2.36,"4":21.5,"5":113,"6":1.41,"7":1.39,"8":0.34,"9":1.14,"10":9.4,"11":0.57,"12":1.33,"13":550},{"0":3,"1":13.5,"2":3.12,"3":2.62,"4":24.0,"5":123,"6":1.4,"7":1.57,"8":0.22,"9":1.25,"10":8.6,"11":0.59,"12":1.3,"13":500},{"0":3,"1":12.79,"2":2.67,"3":2.48,"4":22.0,"5":112,"6":1.48,"7":1.36,"8":0.24,"9":1.26,"10":10.8,"11":0.48,"12":1.47,"13":480},{"0":3,"1":13.11,"2":1.9,"3":2.75,"4":25.5,"5":116,"6":2.2,"7":1.28,"8":0.26,"9":1.56,"10":7.1,"11":0.61,"12":1.33,"13":425},{"0":3,"1":13.23,"2":3.3,"3":2.28,"4":18.5,"5":98,"6":1.8,"7":0.83,"8":0.61,"9":1.87,"10":10.52,"11":0.56,"12":1.51,"13":675},{"0":3,"1":12.58,"2":1.29,"3":2.1,"4":20.0,"5":103,"6":1.48,"7":0.58,"8":0.53,"9":1.4,"10":7.6,"11":0.58,"12":1.55,"13":640},{"0":3,"1":13.17,"2":5.19,"3":2.32,"4":22.0,"5":93,"6":1.74,"7":0.63,"8":0.61,"9":1.55,"10":7.9,"11":0.6,"12":1.48,"13":725},{"0":3,"1":13.84,"2":4.12,"3":2.38,"4":19.5,"5":89,"6":1.8,"7":0.83,"8":0.48,"9":1.56,"10":9.01,"11":0.57,"12":1.64,"13":480},{"0":3,"1":12.45,"2":3.03,"3":2.64,"4":27.0,"5":97,"6":1.9,"7":0.58,"8":0.63,"9":1.14,"10":7.5,"11":0.67,"12":1.73,"13":880},{"0":3,"1":14.34,"2":1.68,"3":2.7,"4":25.0,"5":98,"6":2.8,"7":1.31,"8":0.53,"9":2.7,"10":13.0,"11":0.57,"12

In [228]:
data = '{"id": 1,"name": "Nabeel Rizvi","email": "nabeel@example.com","isActive": true,"roles": ["Admin", "Developer"]}'
df = pd.read_json(StringIO(data))
df.to_json(orient='records')

'[{"id":1,"name":"Nabeel Rizvi","email":"nabeel@example.com","isActive":true,"roles":"Admin"},{"id":1,"name":"Nabeel Rizvi","email":"nabeel@example.com","isActive":true,"roles":"Developer"}]'

In [231]:
df.to_json()

'{"0":{"0":1,"1":1,"2":1,"3":1,"4":1,"5":1,"6":1,"7":1,"8":1,"9":1,"10":1,"11":1,"12":1,"13":1,"14":1,"15":1,"16":1,"17":1,"18":1,"19":1,"20":1,"21":1,"22":1,"23":1,"24":1,"25":1,"26":1,"27":1,"28":1,"29":1,"30":1,"31":1,"32":1,"33":1,"34":1,"35":1,"36":1,"37":1,"38":1,"39":1,"40":1,"41":1,"42":1,"43":1,"44":1,"45":1,"46":1,"47":1,"48":1,"49":1,"50":1,"51":1,"52":1,"53":1,"54":1,"55":1,"56":1,"57":1,"58":1,"59":2,"60":2,"61":2,"62":2,"63":2,"64":2,"65":2,"66":2,"67":2,"68":2,"69":2,"70":2,"71":2,"72":2,"73":2,"74":2,"75":2,"76":2,"77":2,"78":2,"79":2,"80":2,"81":2,"82":2,"83":2,"84":2,"85":2,"86":2,"87":2,"88":2,"89":2,"90":2,"91":2,"92":2,"93":2,"94":2,"95":2,"96":2,"97":2,"98":2,"99":2,"100":2,"101":2,"102":2,"103":2,"104":2,"105":2,"106":2,"107":2,"108":2,"109":2,"110":2,"111":2,"112":2,"113":2,"114":2,"115":2,"116":2,"117":2,"118":2,"119":2,"120":2,"121":2,"122":2,"123":2,"124":2,"125":2,"126":2,"127":2,"128":2,"129":2,"130":3,"131":3,"132":3,"133":3,"134":3,"135":3,"136":3,"137":3,"138":3,"139":3,"140":3,"141":3,"142":3,"143":3,"144":3,"145":3,"146":3,"147":3,"148":3,"149":3,"150":3,"151":3,"152":3,"153":3,"154":3,"155":3,"156":3,"157":3,"158":3,"159":3,"160":3,"161":3,"162":3,"163":3,"164":3,"165":3,"166":3,"167":3,"168":3,"169":3,"170":3,"171":3,"172":3,"173":3,"174":3,"175":3,"176":3,"177":3},"1":{"0":14.23,"1":13.2,"2":13.16,"3":14.37,"4":13.24,"5":14.2,"6":14.39,"7":14.06,"8":14.83,"9":13.86,"10":14.1,"11":14.12,"12":13.75,"13":14.75,"14":14.38,"15":13.63,"16":14.3,"17":13.83,"18":14.19,"19":13.64,"20":14.06,"21":12.93,"22":13.71,"23":12.85,"24":13.5,"25":13.05,"26":13.39,"27":13.3,"28":13.87,"29":14.02,"30":13.73,"31":13.58,"32":13.68,"33":13.76,"34":13.51,"35":13.48,"36":13.28,"37":13.05,"38":13.07,"39":14.22,"40":13.56,"41":13.41,"42":13.88,"43":13.24,"44":13.05,"45":14.21,"46":14.38,"47":13.9,"48":14.1,"49":13.94,"50":13.05,"51":13.83,"52":13.82,"53":13.77,"54":13.74,"55":13.56,"56":14.22,"57":13.29,"58":13.72,"59":12.37,"60":12.33,"61":12.64,"62":13.67,"63":12.37,"64":12.17,"65":12.37,"66":13.11,"67":12.37,"68":13.34,"69":12.21,"70":12.29,"71":13.86,"72":13.49,"73":12.99,"74":11.96,"75":11.66,"76":13.03,"77":11.84,"78":12.33,"79":12.7,"80":12.0,"81":12.72,"82":12.08,"83":13.05,"84":11.84,"85":12.67,"86":12.16,"87":11.65,"88":11.64,"89":12.08,"90":12.08,"91":12.0,"92":12.69,"93":12.29,"94":11.62,"95":12.47,"96":11.81,"97":12.29,"98":12.37,"99":12.29,"100":12.08,"101":12.6,"102":12.34,"103":11.82,"104":12.51,"105":12.42,"106":12.25,"107":12.72,"108":12.22,"109":11.61,"110":11.46,"111":12.52,"112":11.76,"113":11.41,"114":12.08,"115":11.03,"116":11.82,"117":12.42,"118":12.77,"119":12.0,"120":11.45,"121":11.56,"122":12.42,"123":13.05,"124":11.87,"125":12.07,"126":12.43,"127":11.79,"128":12.37,"129":12.04,"130":12.86,"131":12.88,"132":12.81,"133":12.7,"134":12.51,"135":12.6,"136":12.25,"137":12.53,"138":13.49,"139":12.84,"140":12.93,"141":13.36,"142":13.52,"143":13.62,"144":12.25,"145":13.16,"146":13.88,"147":12.87,"148":13.32,"149":13.08,"150":13.5,"151":12.79,"152":13.11,"153":13.23,"154":12.58,"155":13.17,"156":13.84,"157":12.45,"158":14.34,"159":13.48,"160":12.36,"161":13.69,"162":12.85,"163":12.96,"164":13.78,"165":13.73,"166":13.45,"167":12.82,"168":13.58,"169":13.4,"170":12.2,"171":12.77,"172":14.16,"173":13.71,"174":13.4,"175":13.27,"176":13.17,"177":14.13},"2":{"0":1.71,"1":1.78,"2":2.36,"3":1.95,"4":2.59,"5":1.76,"6":1.87,"7":2.15,"8":1.64,"9":1.35,"10":2.16,"11":1.48,"12":1.73,"13":1.73,"14":1.87,"15":1.81,"16":1.92,"17":1.57,"18":1.59,"19":3.1,"20":1.63,"21":3.8,"22":1.86,"23":1.6,"24":1.81,"25":2.05,"26":1.77,"27":1.72,"28":1.9,"29":1.68,"30":1.5,"31":1.66,"32":1.83,"33":1.53,"34":1.8,"35":1.81,"36":1.64,"37":1.65,"38":1.5,"39":3.99,"40":1.71,"41":3.84,"42":1.89,"43":3.98,"44":1.77,"45":4.04,"46":3.59,"47":1.68,"48":2.02,"49":1.73,"50":1.73,"51":1.65,"52":1.75,"53":1.9,"54":1.67,"55":1.73,"56":1.7,"57":1.97,"58":1.43,"59":0.94,"60":1.1,"61":1.36,"62":1.25,"63":1.13,"64":1.45,"65":1.21,"66":1.01,"67":1.17,"68":0.94,"69":1.19,"70":1.61,"71":1.51,"72":1.66,"73":1.67,"74":1.09,"75":1.88,"76":0.9,"77":2.89,"78":0.99,"79":3.87,"80":0.92,"81":1.81,"82":1.13,"83":3.86,"84":0.89,"85":0.98,"86":1.61,"87":1.67,"88":2.06,"89":1.33,"90":1.83,"91":1.51,"92":1.53,"93":2.83,"94":1.99,"95":1.52,"96":2.12,"97":1.41,"98":1.07,"99":3.17,"100":2.08,"101":1.34,"102":2.45,"103":1.72,"104":1.73,"105":2.55,"106":1.73,"107":1.75,"108":1.29,"109":1.35,"110":3.74,"111":2.43,"112":2.68,"113":0.74,"114":1.39,"115":1.51,"116":1.47,"117":1.61,"118":3.43,"119":3.43,"120":2.4,"121":2.05,"122":4.43,"123":5.8,"124":4.31,"125":2.16,"126":1.53,"127":2.13,"128":1.63,"129":4.3,"130":1.35,"131":2.99,"132":2.31,"133":3.55,"134":1.24,"135":2.46,"136":4.72,"137":5.51,"138":3.59,"139":2.96,"140":2.81,"141":2.56,"142":3.17,"143":4.95,"144":3.88,"145":3.57,"146":5.04,"147":4.61,"148":3.24,"149":3.9,"150":3.12,"151":2.67,"152":1.9,"153":3.3,"154":1.29,"155":5.19,"156":4.12,"157":3.03,"158":1.68,"159":1.67,"160":3.83,"161":3.26,"162":3.27,"163":3.45,"164":2.76,"165":4.36,"166":3.7,"167":3.37,"168":2.58,"169":4.6,"170":3.03,"171":2.39,"172":2.51,"173":5.65,"174":3.91,"175":4.28,"176":2.59,"177":4.1},"3":{"0":2.43,"1":2.14,"2":2.67,"3":2.5,"4":2.87,"5":2.45,"6":2.45,"7":2.61,"8":2.17,"9":2.27,"10":2.3,"11":2.32,"12":2.41,"13":2.39,"14":2.38,"15":2.7,"16":2.72,"17":2.62,"18":2.48,"19":2.56,"20":2.28,"21":2.65,"22":2.36,"23":2.52,"24":2.61,"25":3.22,"26":2.62,"27":2.14,"28":2.8,"29":2.21,"30":2.7,"31":2.36,"32":2.36,"33":2.7,"34":2.65,"35":2.41,"36":2.84,"37":2.55,"38":2.1,"39":2.51,"40":2.31,"41":2.12,"42":2.59,"43":2.29,"44":2.1,"45":2.44,"46":2.28,"47":2.12,"48":2.4,"49":2.27,"50":2.04,"51":2.6,"52":2.42,"53":2.68,"54":2.25,"55":2.46,"56":2.3,"57":2.68,"58":2.5,"59":1.36,"60":2.28,"61":2.02,"62":1.92,"63":2.16,"64":2.53,"65":2.56,"66":1.7,"67":1.92,"68":2.36,"69":1.75,"70":2.21,"71":2.67,"72":2.24,"73":2.6,"74":2.3,"75":1.92,"76":1.71,"77":2.23,"78":1.95,"79":2.4,"80":2.0,"81":2.2,"82":2.51,"83":2.32,"84":2.58,"85":2.24,"86":2.31,"87":2.62,"88":2.46,"89":2.3,"90":2.32,"91":2.42,"92":2.26,"93":2.22,"94":2.28,"95":2.2,"96":2.74,"97":1.98,"98":2.1,"99":2.21,"100":1.7,"101":1.9,"102":2.46,"103":1.88,"104":1.98,"105":2.27,"106":2.12,"107":2.28,"108":1.94,"109":2.7,"110":1.82,"111":2.17,"112":2.92,"113":2.5,"114":2.5,"115":2.2,"116":1.99,"117":2.19,"118":1.98,"119":2.0,"120":2.42,"121":3.23,"122":2.73,"123":2.13,"124":2.39,"125":2.17,"126":2.29,"127":2.78,"128":2.3,"129":2.38,"130":2.32,"131":2.4,"132":2.4,"133":2.36,"134":2.25,"135":2.2,"136":2.54,"137":2.64,"138":2.19,"139":2.61,"140":2.7,"141":2.35,"142":2.72,"143":2.35,"144":2.2,"145":2.15,"146":2.23,"147":2.48,"148":2.38,"149":2.36,"150":2.62,"151":2.48,"152":2.75,"153":2.28,"154":2.1,"155":2.32,"156":2.38,"157":2.64,"158":2.7,"159":2.64,"160":2.38,"161":2.54,"162":2.58,"163":2.35,"164":2.3,"165":2.26,"166":2.6,"167":2.3,"168":2.69,"169":2.86,"170":2.32,"171":2.28,"172":2.48,"173":2.45,"174":2.48,"175":2.26,"176":2.37,"177":2.74},"4":{"0":15.6,"1":11.2,"2":18.6,"3":16.8,"4":21.0,"5":15.2,"6":14.6,"7":17.6,"8":14.0,"9":16.0,"10":18.0,"11":16.8,"12":16.0,"13":11.4,"14":12.0,"15":17.2,"16":20.0,"17":20.0,"18":16.5,"19":15.2,"20":16.0,"21":18.6,"22":16.6,"23":17.8,"24":20.0,"25":25.0,"26":16.1,"27":17.0,"28":19.4,"29":16.0,"30":22.5,"31":19.1,"32":17.2,"33":19.5,"34":19.0,"35":20.5,"36":15.5,"37":18.0,"38":15.5,"39":13.2,"40":16.2,"41":18.8,"42":15.0,"43":17.5,"44":17.0,"45":18.9,"46":16.0,"47":16.0,"48":18.8,"49":17.4,"50":12.4,"51":17.2,"52":14.0,"53":17.1,"54":16.4,"55":20.5,"56":16.3,"57":16.8,"58":16.7,"59":10.6,"60":16.0,"61":16.8,"62":18.0,"63":19.0,"64":19.0,"65":18.1,"66":15.0,"67":19.6,"68":17.0,"69":16.8,"70":20.4,"71":25.0,"72":24.0,"73":30.0,"74":21.0,"75":16.0,"76":16.0,"77":18.0,"78":14.8,"79":23.0,"80":19.0,"81":18.8,"82":24.0,"83":22.5,"84":18.0,"85":18.0,"86":22.8,"87":26.0,"88":21.6,"89":23.6,"90":18.5,"91":22.0,"92":20.7,"93":18.0,"94":18.0,"95":19.0,"96":21.5,"97":16.0,"98":18.5,"99":18.0,"100":17.5,"101":18.5,"102":21.0,"103":19.5,"104":20.5,"105":22.0,"106":19.0,"107":22.5,"108":19.0,"109":20.0,"110":19.5,"111":21.0,"112":20.0,"113":21.0,"114":22.5,"115":21.5,"116":20.8,"117":22.5,"118":16.0,"119":19.0,"120":20.0,"121":28.5,"122":26.5,"123":21.5,"124":21.0,"125":21.0,"126":21.5,"127":28.5,"128":24.5,"129":22.0,"130":18.0,"131":20.0,"132":24.0,"133":21.5,"134":17.5,"135":18.5,"136":21.0,"137":25.0,"138":19.5,"139":24.0,"140":21.0,"141":20.0,"142":23.5,"143":20.0,"144":18.5,"145":21.0,"146":20.0,"147":21.5,"148":21.5,"149":21.5,"150":24.0,"151":22.0,"152":25.5,"153":18.5,"154":20.0,"155":22.0,"156":19.5,"157":27.0,"158":25.0,"159":22.5,"160":21.0,"161":20.0,"162":22.0,"163":18.5,"164":22.0,"165":22.5,"166":23.0,"167":19.5,"168":24.5,"169":25.0,"170":19.0,"171":19.5,"172":20.0,"173":20.5,"174":23.0,"175":20.0,"176":20.0,"177":24.5},"5":{"0":127,"1":100,"2":101,"3":113,"4":118,"5":112,"6":96,"7":121,"8":97,"9":98,"10":105,"11":95,"12":89,"13":91,"14":102,"15":112,"16":120,"17":115,"18":108,"19":116,"20":126,"21":102,"22":101,"23":95,"24":96,"25":124,"26":93,"27":94,"28":107,"29":96,"30":101,"31":106,"32":104,"33":132,"34":110,"35":100,"36":110,"37":98,"38":98,"39":128,"40":117,"41":90,"42":101,"43":103,"44":107,"45":111,"46":102,"47":101,"48":103,"49":108,"50":92,"51":94,"52":111,"53":115,"54":118,"55":116,"56":118,"57":102,"58":108,"59":88,"60":101,"61":100,"62":94,"63":87,"64":104,"65":98,"66":78,"67":78,"68":110,"69":151,"70":103,"71":86,"72":87,"73":139,"74":101,"75":97,"76":86,"77":112,"78":136,"79":101,"80":86,"81":86,"82":78,"83":85,"84":94,"85":99,"86":90,"87":88,"88":84,"89":70,"90":81,"91":86,"92":80,"93":88,"94":98,"95":162,"96":134,"97":85,"98":88,"99":88,"100":97,"101":88,"102":98,"103":86,"104":85,"105":90,"106":80,"107":84,"108":92,"109":94,"110":107,"111":88,"112":103,"113":88,"114":84,"115":85,"116":86,"117":108,"118":80,"119":87,"120":96,"121":119,"122":102,"123":86,"124":82,"125":85,"126":86,"127":92,"128":88,"129":80,"130":122,"131":104,"132":98,"133":106,"134":85,"135":94,"136":89,"137":96,"138":88,"139":101,"140":96,"141":89,"142":97,"143":92,"144":112,"145":102,"146":80,"147":86,"148":92,"149":113,"150":123,"151":112,"152":116,"153":98,"154":103,"155":93,"156":89,"157":97,"158":98,"159":89,"160":88,"161":107,"162":106,"163":106,"164":90,"165":88,"166":111,"167":88,"168":105,"169":112,"170":96,"171":86,"172":91,"173":95,"174":102,"175":120,"176":120,"177":96},"6":{"0":2.8,"1":2.65,"2":2.8,"3":3.85,"4":2.8,"5":3.27,"6":2.5,"7":2.6,"8":2.8,"9":2.98,"10":2.95,"11":2.2,"12":2.6,"13":3.1,"14":3.3,"15":2.85,"16":2.8,"17":2.95,"18":3.3,"19":2.7,"20":3.0,"21":2.41,"22":2.61,"23":2.48,"24":2.53,"25":2.63,"26":2.85,"27":2.4,"28":2.95,"29":2.65,"30":3.0,"31":2.86,"32":2.42,"33":2.95,"34":2.35,"35":2.7,"36":2.6,"37":2.45,"38":2.4,"39":3.0,"40":3.15,"41":2.45,"42":3.25,"43":2.64,"44":3.0,"45":2.85,"46":3.25,"47":3.1,"48":2.75,"49":2.88,"50":2.72,"51":2.45,"52":3.88,"53":3.0,"54":2.6,"55":2.96,"56":3.2,"57":3.0,"58":3.4,"59":1.98,"60":2.05,"61":2.02,"62":2.1,"63":3.5,"64":1.89,"65":2.42,"66":2.98,"67":2.11,"68":2.53,"69":1.85,"70":1.1,"71":2.95,"72":1.88,"73":3.3,"74":3.38,"75":1.61,"76":1.95,"77":1.72,"78":1.9,"79":2.83,"80":2.42,"81":2.2,"82":2.0,"83":1.65,"84":2.2,"85":2.2,"86":1.78,"87":1.92,"88":1.95,"89":2.2,"90":1.6,"91":1.45,"92":1.38,"93":2.45,"94":3.02,"95":2.5,"96":1.6,"97":2.55,"98":3.52,"99":2.85,"100":2.23,"101":1.45,"102":2.56,"103":2.5,"104":2.2,"105":1.68,"106":1.65,"107":1.38,"108":2.36,"109":2.74,"110":3.18,"111":2.55,"112":1.75,"113":2.48,"114":2.56,"115":2.46,"116":1.98,"117":2.0,"118":1.63,"119":2.0,"120":2.9,"121":3.18,"122":2.2,"123":2.62,"124":2.86,"125":2.6,"126":2.74,"127":2.13,"128":2.22,"129":2.1,"130":1.51,"131":1.3,"132":1.15,"133":1.7,"134":2.0,"135":1.62,"136":1.38,"137":1.79,"138":1.62,"139":2.32,"140":1.54,"141":1.4,"142":1.55,"143":2.0,"144":1.38,"145":1.5,"146":0.98,"147":1.7,"148":1.93,"149":1.41,"150":1.4,"151":1.48,"152":2.2,"153":1.8,"154":1.48,"155":1.74,"156":1.8,"157":1.9,"158":2.8,"159":2.6,"160":2.3,"161":1.83,"162":1.65,"163":1.39,"164":1.35,"165":1.28,"166":1.7,"167":1.48,"168":1.55,"169":1.98,"170":1.25,"171":1.39,"172":1.68,"173":1.68,"174":1.8,"175":1.59,"176":1.65,"177":2.05},"7":{"0":3.06,"1":2.76,"2":3.24,"3":3.49,"4":2.69,"5":3.39,"6":2.52,"7":2.51,"8":2.98,"9":3.15,"10":3.32,"11":2.43,"12":2.76,"13":3.69,"14":3.64,"15":2.91,"16":3.14,"17":3.4,"18":3.93,"19":3.03,"20":3.17,"21":2.41,"22":2.88,"23":2.37,"24":2.61,"25":2.68,"26":2.94,"27":2.19,"28":2.97,"29":2.33,"30":3.25,"31":3.19,"32":2.69,"33":2.74,"34":2.53,"35":2.98,"36":2.68,"37":2.43,"38":2.64,"39":3.04,"40":3.29,"41":2.68,"42":3.56,"43":2.63,"44":3.0,"45":2.65,"46":3.17,"47":3.39,"48":2.92,"49":3.54,"50":3.27,"51":2.99,"52":3.74,"53":2.79,"54":2.9,"55":2.78,"56":3.0,"57":3.23,"58":3.67,"59":0.57,"60":1.09,"61":1.41,"62":1.79,"63":3.1,"64":1.75,"65":2.65,"66":3.18,"67":2.0,"68":1.3,"69":1.28,"70":1.02,"71":2.86,"72":1.84,"73":2.89,"74":2.14,"75":1.57,"76":2.03,"77":1.32,"78":1.85,"79":2.55,"80":2.26,"81":2.53,"82":1.58,"83":1.59,"84":2.21,"85":1.94,"86":1.69,"87":1.61,"88":1.69,"89":1.59,"90":1.5,"91":1.25,"92":1.46,"93":2.25,"94":2.26,"95":2.27,"96":0.99,"97":2.5,"98":3.75,"99":2.99,"100":2.17,"101":1.36,"102":2.11,"103":1.64,"104":1.92,"105":1.84,"106":2.03,"107":1.76,"108":2.04,"109":2.92,"110":2.58,"111":2.27,"112":2.03,"113":2.01,"114":2.29,"115":2.17,"116":1.6,"117":2.09,"118":1.25,"119":1.64,"120":2.79,"121":5.08,"122":2.13,"123":2.65,"124":3.03,"125":2.65,"126":3.15,"127":2.24,"128":2.45,"129":1.75,"130":1.25,"131":1.22,"132":1.09,"133":1.2,"134":0.58,"135":0.66,"136":0.47,"137":0.6,"138":0.48,"139":0.6,"140":0.5,"141":0.5,"142":0.52,"143":0.8,"144":0.78,"145":0.55,"146":0.34,"147":0.65,"148":0.76,"149":1.39,"150":1.57,"151":1.36,"152":1.28,"153":0.83,"154":0.58,"155":0.63,"156":0.83,"157":0.58,"158":1.31,"159":1.1,"160":0.92,"161":0.56,"162":0.6,"163":0.7,"164":0.68,"165":0.47,"166":0.92,"167":0.66,"168":0.84,"169":0.96,"170":0.49,"171":0.51,"172":0.7,"173":0.61,"174":0.75,"175":0.69,"176":0.68,"177":0.76},"8":{"0":0.28,"1":0.26,"2":0.3,"3":0.24,"4":0.39,"5":0.34,"6":0.3,"7":0.31,"8":0.29,"9":0.22,"10":0.22,"11":0.26,"12":0.29,"13":0.43,"14":0.29,"15":0.3,"16":0.33,"17":0.4,"18":0.32,"19":0.17,"20":0.24,"21":0.25,"22":0.27,"23":0.26,"24":0.28,"25":0.47,"26":0.34,"27":0.27,"28":0.37,"29":0.26,"30":0.29,"31":0.22,"32":0.42,"33":0.5,"34":0.29,"35":0.26,"36":0.34,"37":0.29,"38":0.28,"39":0.2,"40":0.34,"41":0.27,"42":0.17,"43":0.32,"44":0.28,"45":0.3,"46":0.27,"47":0.21,"48":0.32,"49":0.32,"50":0.17,"51":0.22,"52":0.32,"53":0.39,"54":0.21,"55":0.2,"56":0.26,"57":0.31,"58":0.19,"59":0.28,"60":0.63,"61":0.53,"62":0.32,"63":0.19,"64":0.45,"65":0.37,"66":0.26,"67":0.27,"68":0.55,"69":0.14,"70":0.37,"71":0.21,"72":0.27,"73":0.21,"74":0.13,"75":0.34,"76":0.24,"77":0.43,"78":0.35,"79":0.43,"80":0.3,"81":0.26,"82":0.4,"83":0.61,"84":0.22,"85":0.3,"86":0.43,"87":0.4,"88":0.48,"89":0.42,"90":0.52,"91":0.5,"92":0.58,"93":0.25,"94":0.17,"95":0.32,"96":0.14,"97":0.29,"98":0.24,"99":0.45,"100":0.26,"101":0.29,"102":0.34,"103":0.37,"104":0.32,"105":0.66,"106":0.37,"107":0.48,"108":0.39,"109":0.29,"110":0.24,"111":0.26,"112":0.6,"113":0.42,"114":0.43,"115":0.52,"116":0.3,"117":0.34,"118":0.43,"119":0.37,"120":0.32,"121":0.47,"122":0.43,"123":0.3,"124":0.21,"125":0.37,"126":0.39,"127":0.58,"128":0.4,"129":0.42,"130":0.21,"131":0.24,"132":0.27,"133":0.17,"134":0.6,"135":0.63,"136":0.53,"137":0.63,"138":0.58,"139":0.53,"140":0.53,"141":0.37,"142":0.5,"143":0.47,"144":0.29,"145":0.43,"146":0.4,"147":0.47,"148":0.45,"149":0.34,"150":0.22,"151":0.24,"152":0.26,"153":0.61,"154":0.53,"155":0.61,"156":0.48,"157":0.63,"158":0.53,"159":0.52,"160":0.5,"161":0.5,"162":0.6,"163":0.4,"164":0.41,"165":0.52,"166":0.43,"167":0.4,"168":0.39,"169":0.27,"170":0.4,"171":0.48,"172":0.44,"173":0.52,"174":0.43,"175":0.43,"176":0.53,"177":0.56},"9":{"0":2.29,"1":1.28,"2":2.81,"3":2.18,"4":1.82,"5":1.97,"6":1.98,"7":1.25,"8":1.98,"9":1.85,"10":2.38,"11":1.57,"12":1.81,"13":2.81,"14":2.96,"15":1.46,"16":1.97,"17":1.72,"18":1.86,"19":1.66,"20":2.1,"21":1.98,"22":1.69,"23":1.46,"24":1.66,"25":1.92,"26":1.45,"27":1.35,"28":1.76,"29":1.98,"30":2.38,"31":1.95,"32":1.97,"33":1.35,"34":1.54,"35":1.86,"36":1.36,"37":1.44,"38":1.37,"39":2.08,"40":2.34,"41":1.48,"42":1.7,"43":1.66,"44":2.03,"45":1.25,"46":2.19,"47":2.14,"48":2.38,"49":2.08,"50":2.91,"51":2.29,"52":1.87,"53":1.68,"54":1.62,"55":2.45,"56":2.03,"57":1.66,"58":2.04,"59":0.42,"60":0.41,"61":0.62,"62":0.73,"63":1.87,"64":1.03,"65":2.08,"66":2.28,"67":1.04,"68":0.42,"69":2.5,"70":1.46,"71":1.87,"72":1.03,"73":1.96,"74":1.65,"75":1.15,"76":1.46,"77":0.95,"78":2.76,"79":1.95,"80":1.43,"81":1.77,"82":1.4,"83":1.62,"84":2.35,"85":1.46,"86":1.56,"87":1.34,"88":1.35,"89":1.38,"90":1.64,"91":1.63,"92":1.62,"93":1.99,"94":1.35,"95":3.28,"96":1.56,"97":1.77,"98":1.95,"99":2.81,"100":1.4,"101":1.35,"102":1.31,"103":1.42,"104":1.48,"105":1.42,"106":1.63,"107":1.63,"108":2.08,"109":2.49,"110":3.58,"111":1.22,"112":1.05,"113":1.44,"114":1.04,"115":2.01,"116":1.53,"117":1.61,"118":0.83,"119":1.87,"120":1.83,"121":1.87,"122":1.71,"123":2.01,"124":2.91,"125":1.35,"126":1.77,"127":1.76,"128":1.9,"129":1.35,"130":0.94,"131":0.83,"132":0.83,"133":0.84,"134":1.25,"135":0.94,"136":0.8,"137":1.1,"138":0.88,"139":0.81,"140":0.75,"141":0.64,"142":0.55,"143":1.02,"144":1.14,"145":1.3,"146":0.68,"147":0.86,"148":1.25,"149":1.14,"150":1.25,"151":1.26,"152":1.56,"153":1.87,"154":1.4,"155":1.55,"156":1.56,"157":1.14,"158":2.7,"159":2.29,"160":1.04,"161":0.8,"162":0.96,"163":0.94,"164":1.03,"165":1.15,"166":1.46,"167":0.97,"168":1.54,"169":1.11,"170":0.73,"171":0.64,"172":1.24,"173":1.06,"174":1.41,"175":1.35,"176":1.46,"177":1.35},"10":{"0":5.64,"1":4.38,"2":5.68,"3":7.8,"4":4.32,"5":6.75,"6":5.25,"7":5.05,"8":5.2,"9":7.22,"10":5.75,"11":5.0,"12":5.6,"13":5.4,"14":7.5,"15":7.3,"16":6.2,"17":6.6,"18":8.7,"19":5.1,"20":5.65,"21":4.5,"22":3.8,"23":3.93,"24":3.52,"25":3.58,"26":4.8,"27":3.95,"28":4.5,"29":4.7,"30":5.7,"31":6.9,"32":3.84,"33":5.4,"34":4.2,"35":5.1,"36":4.6,"37":4.25,"38":3.7,"39":5.1,"40":6.13,"41":4.28,"42":5.43,"43":4.36,"44":5.04,"45":5.24,"46":4.9,"47":6.1,"48":6.2,"49":8.9,"50":7.2,"51":5.6,"52":7.05,"53":6.3,"54":5.85,"55":6.25,"56":6.38,"57":6.0,"58":6.8,"59":1.95,"60":3.27,"61":5.75,"62":3.8,"63":4.45,"64":2.95,"65":4.6,"66":5.3,"67":4.68,"68":3.17,"69":2.85,"70":3.05,"71":3.38,"72":3.74,"73":3.35,"74":3.21,"75":3.8,"76":4.6,"77":2.65,"78":3.4,"79":2.57,"80":2.5,"81":3.9,"82":2.2,"83":4.8,"84":3.05,"85":2.62,"86":2.45,"87":2.6,"88":2.8,"89":1.74,"90":2.4,"91":3.6,"92":3.05,"93":2.15,"94":3.25,"95":2.6,"96":2.5,"97":2.9,"98":4.5,"99":2.3,"100":3.3,"101":2.45,"102":2.8,"103":2.06,"104":2.94,"105":2.7,"106":3.4,"107":3.3,"108":2.7,"109":2.65,"110":2.9,"111":2.0,"112":3.8,"113":3.08,"114":2.9,"115":1.9,"116":1.95,"117":2.06,"118":3.4,"119":1.28,"120":3.25,"121":6.0,"122":2.08,"123":2.6,"124":2.8,"125":2.76,"126":3.94,"127":3.0,"128":2.12,"129":2.6,"130":4.1,"131":5.4,"132":5.7,"133":5.0,"134":5.45,"135":7.1,"136":3.85,"137":5.0,"138":5.7,"139":4.92,"140":4.6,"141":5.6,"142":4.35,"143":4.4,"144":8.21,"145":4.0,"146":4.9,"147":7.65,"148":8.42,"149":9.4,"150":8.6,"151":10.8,"152":7.1,"153":10.52,"154":7.6,"155":7.9,"156":9.01,"157":7.5,"158":13.0,"159":11.75,"160":7.65,"161":5.88,"162":5.58,"163":5.28,"164":9.58,"165":6.62,"166":10.68,"167":10.26,"168":8.66,"169":8.5,"170":5.5,"171":9.899999,"172":9.7,"173":7.7,"174":7.3,"175":10.2,"176":9.3,"177":9.2},"11":{"0":1.04,"1":1.05,"2":1.03,"3":0.86,"4":1.04,"5":1.05,"6":1.02,"7":1.06,"8":1.08,"9":1.01,"10":1.25,"11":1.17,"12":1.15,"13":1.25,"14":1.2,"15":1.28,"16":1.07,"17":1.13,"18":1.23,"19":0.96,"20":1.09,"21":1.03,"22":1.11,"23":1.09,"24":1.12,"25":1.13,"26":0.92,"27":1.02,"28":1.25,"29":1.04,"30":1.19,"31":1.09,"32":1.23,"33":1.25,"34":1.1,"35":1.04,"36":1.09,"37":1.12,"38":1.18,"39":0.89,"40":0.95,"41":0.91,"42":0.88,"43":0.82,"44":0.88,"45":0.87,"46":1.04,"47":0.91,"48":1.07,"49":1.12,"50":1.12,"51":1.24,"52":1.

In [232]:
df.to_json(orient='records')

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},{"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},{"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},{"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},{"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},{"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},{"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},{"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},{"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},{"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},{"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},{"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},{"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},{"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},{"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},{"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},{"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},{"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},{"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},{"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},{"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},{"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},{"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},{"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},{"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},{"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},{"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},{"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},{"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},{"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},{"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},{"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},{"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},{"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},{"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},{"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},{"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},{"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},{"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},{"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},{"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},{"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},{"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},{"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},{"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},{"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},{"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},{"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},{"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},{"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},{"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},{"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},{"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},{"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},{"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},{"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},{"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},{"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},{"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},{"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},{"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},{"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},{"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},{"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},{"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},{"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},{"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},{"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},{"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},{"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},{"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},{"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},{"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},{"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},{"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},{"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},{"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},{"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},{"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},{"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},{"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},{"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},{"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},{"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},{"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},{"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},{"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},{"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},{"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},{"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},{"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},{"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},{"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},{"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},{"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},{"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},{"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},{"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},{"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},{"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},{"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},{"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},{"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},{"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},{"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},{"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},{"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},{"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},{"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},{"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},{"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},{"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},{"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},{"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},{"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},{"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},{"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},{"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},{"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},{"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},{"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},{"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},{"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},{"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},{"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},{"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},{"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},{"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},{"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},{"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},{"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},{"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},{"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},{"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53,"9":0.75,"10":4.6,"11":0.77,"12":2.31,"13":600},{"0":3,"1":13.36,"2":2.56,"3":2.35,"4":20.0,"5":89,"6":1.4,"7":0.5,"8":0.37,"9":0.64,"10":5.6,"11":0.7,"12":2.47,"13":780},{"0":3,"1":13.52,"2":3.17,"3":2.72,"4":23.5,"5":97,"6":1.55,"7":0.52,"8":0.5,"9":0.55,"10":4.35,"11":0.89,"12":2.06,"13":520},{"0":3,"1":13.62,"2":4.95,"3":2.35,"4":20.0,"5":92,"6":2.0,"7":0.8,"8":0.47,"9":1.02,"10":4.4,"11":0.91,"12":2.05,"13":550},{"0":3,"1":12.25,"2":3.88,"3":2.2,"4":18.5,"5":112,"6":1.38,"7":0.78,"8":0.29,"9":1.14,"10":8.21,"11":0.65,"12":2.0,"13":855},{"0":3,"1":13.16,"2":3.57,"3":2.15,"4":21.0,"5":102,"6":1.5,"7":0.55,"8":0.43,"9":1.3,"10":4.0,"11":0.6,"12":1.68,"13":830},{"0":3,"1":13.88,"2":5.04,"3":2.23,"4":20.0,"5":80,"6":0.98,"7":0.34,"8":0.4,"9":0.68,"10":4.9,"11":0.58,"12":1.33,"13":415},{"0":3,"1":12.87,"2":4.61,"3":2.48,"4":21.5,"5":86,"6":1.7,"7":0.65,"8":0.47,"9":0.86,"10":7.65,"11":0.54,"12":1.86,"13":625},{"0":3,"1":13.32,"2":3.24,"3":2.38,"4":21.5,"5":92,"6":1.93,"7":0.76,"8":0.45,"9":1.25,"10":8.42,"11":0.55,"12":1.62,"13":650},{"0":3,"1":13.08,"2":3.9,"3":2.36,"4":21.5,"5":113,"6":1.41,"7":1.39,"8":0.34,"9":1.14,"10":9.4,"11":0.57,"12":1.33,"13":550},{"0":3,"1":13.5,"2":3.12,"3":2.62,"4":24.0,"5":123,"6":1.4,"7":1.57,"8":0.22,"9":1.25,"10":8.6,"11":0.59,"12":1.3,"13":500},{"0":3,"1":12.79,"2":2.67,"3":2.48,"4":22.0,"5":112,"6":1.48,"7":1.36,"8":0.24,"9":1.26,"10":10.8,"11":0.48,"12":1.47,"13":480},{"0":3,"1":13.11,"2":1.9,"3":2.75,"4":25.5,"5":116,"6":2.2,"7":1.28,"8":0.26,"9":1.56,"10":7.1,"11":0.61,"12":1.33,"13":425},{"0":3,"1":13.23,"2":3.3,"3":2.28,"4":18.5,"5":98,"6":1.8,"7":0.83,"8":0.61,"9":1.87,"10":10.52,"11":0.56,"12":1.51,"13":675},{"0":3,"1":12.58,"2":1.29,"3":2.1,"4":20.0,"5":103,"6":1.48,"7":0.58,"8":0.53,"9":1.4,"10":7.6,"11":0.58,"12":1.55,"13":640},{"0":3,"1":13.17,"2":5.19,"3":2.32,"4":22.0,"5":93,"6":1.74,"7":0.63,"8":0.61,"9":1.55,"10":7.9,"11":0.6,"12":1.48,"13":725},{"0":3,"1":13.84,"2":4.12,"3":2.38,"4":19.5,"5":89,"6":1.8,"7":0.83,"8":0.48,"9":1.56,"10":9.01,"11":0.57,"12":1.64,"13":480},{"0":3,"1":12.45,"2":3.03,"3":2.64,"4":27.0,"5":97,"6":1.9,"7":0.58,"8":0.63,"9":1.14,"10":7.5,"11":0.67,"12":1.73,"13":880},{"0":3,"1":14.34,"2":1.68,"3":2.7,"4":25.0,"5":98,"6":2.8,"7":1.31,"8":0.53,"9":2.7,"10":13.0,"11":0.57,"12

### READ HTML CONTENT

In [246]:
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
dfs  = pd.read_html(url)

In [247]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [240]:
len(dfs)

1

In [255]:
url_match = 'https://en.wikipedia.org/wiki/Mobile_country_code'

# Read the table that contains 'Country' in its header
dsf = pd.read_html(url_match, match='Country', header=0)
#forbiden

C:\Users\nabee\AppData\Local\Temp\ipykernel_16700\286991068.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text, match="Country", header=0)

ValueError: No tables found matching pattern 'Country'